[global]
# Configuração mínima para Streamlit Cloud
showWarningOnDirectExecution = false

[logger]
level = "error"

[client]
# Configurações do cliente
showErrorDetails = false
toolbarMode = "minimal"

[server]
# Configurações essenciais do servidor
headless = true
runOnSave = false
port = 8501
enableCORS = false
enableXsrfProtection = false

# Configurações de upload e mensagem
maxUploadSize = 200
maxMessageSize = 200

# Configurações de compressão
enableWebsocketCompression = false

[theme]
# Tema personalizado
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"