# Streamlit secrets configuration
# Este arquivo deve ser configurado no Streamlit Cloud com suas chaves de API

# API Keys - Configure estas variáveis no Streamlit Cloud
# BRASIL_IO_API_KEY = "sua_chave_da_api_brasil_io"
# DISEASE_SH_API_KEY = "sua_chave_da_api_disease_sh"

# URLs das APIs (podem ser públicas)
BRASIL_IO_BASE_URL = "https://api.brasil.io/v1"
DISEASE_SH_BASE_URL = "https://disease.sh/v3/covid-19"

# Configurações da aplicação
APP_TITLE = "Dashboard COVID-19"
APP_DESCRIPTION = "Dashboard interativo para análise de dados de COVID-19 no Brasil e no mundo"